food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:item_id>/', views.FoodDetailView.as_view(), name='food-details'),
    path('<int:item_id>/update/', views.update_food, name='update-item'),
    path('<int:item_id>/delete/', views.delete_food, name='delete-item'),
    path('add/', views.FoodCreateView.as_view(), name='add-item'),
]

foodmenu_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('foods/', include('food.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register-user'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-user'),
    path('profile/', user_views.user_profile, name='user-profile')
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Food(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200)
    desc = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image_url = models.CharField(max_length=500, default="https://wickedwhiskricelake.com/wp-content/uploads/2023/04/EmptyDinnerPlates.jpg")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("food:food-details", kwargs={"item_id": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_images/profilepic.jpg', upload_to='profile_images')
    location = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.user.username

food/forms.py
from django import forms
from .models import Food

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'desc', 'price', 'image_url']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Food
from .forms import FoodForm
from django.views.generic import ListView, DetailView, CreateView

# Create your views here.


class IndexView(ListView):
    model = Food
    template_name = 'food/index.html'
    context_object_name = 'items'

class FoodDetailView(DetailView):
    model = Food
    pk_url_kwarg = 'item_id'
    context_object_name = 'item'
    template_name = 'food/food_details.html'


class FoodCreateView(CreateView):
    model = Food
    fields = ['name', 'desc', 'price', 'image_url']
    template_name = 'food/food_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



def create_food(request):
    form = FoodForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/food_form.html', {'form': form})


def update_food(request, item_id):
    item = Food.objects.get(pk=item_id)
    form = FoodForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/food_form.html', {'form': form})


def delete_food(request, item_id):
    item = Food.objects.get(pk=item_id)
    if request.method == 'POST':
        if request.POST['delete'] == 'confirm':
            item.delete()
            return redirect('food:index')
        else:
            return redirect('food:food-details', item_id=item_id)

    return render(request, 'food/food_delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account has been created.')
            return redirect('users:login-user')
        else:
            return render(request, 'users/register.html', {'form':form})
    else:
        form = RegisterUserForm()
        return render(request, 'users/register.html', {'form':form})
    
@login_required
def user_profile(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}Food Menu{% endblock page_title %}</title>
    <link rel="stylesheet" href={% static 'food/style.css' %}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark-subtle">
        <div class="container-fluid">
            <a class="navbar-brand" href="/foods">FoodMenu</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto d-flex mt-3 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href={% url 'food:add-item' %}>Add Food</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Delete Food</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">View Food</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:logout-user' %}>Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:user-profile' %}>Profile</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:login-user' %}>Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}{% endblock content %}
</body>

</html>

food/templates/food/food_delete.html
{% extends 'food/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.name}}</h2>
    <button type="submit" name="delete" value="confirm">Confirm</button>
    <button type="submit" name="delete" value="cancel">Cancel</button>
</form>
{% endblock content %}

food/templates/food/food_details.html
{% extends 'food/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.image_url}}" alt="" class="card" style="max-height: 300px;">
        </div>
        <div class="col-md-6">
            <h1>{{item.name}}</h1>
            <h2>{{item.desc}}</h2>
            <h5>Rs. {{item.price}}</h5>
            <a href={% url 'food:delete-item' item.id %}>Delete</a>
        </div>
    </div>
</div>
{% endblock content %}

food/templates/food/food_form.html
{% extends 'food/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-4 offset-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title ">
                        Add Food
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
    <ul class="p-0 mt-5">
        {% for item in items %}
        <div class="card mb-3" style="max-width: 50rem;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src={{item.image_url}} class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{item.name}}</h5>
                        <p class="card-text">{{item.desc | truncatewords:20}}</p>
                        <span class="card-text"><small class="text-body-secondary">Rs. {{item.price}}</small></span>
                        <span style="margin-left: 20px;">{{item.author}}</span>
                    </div>
                </div>
                <div class="col-md-2 d-flex align-items-center">
                    <a href={% url 'food:food-details' item.id %} class="btn btn-success">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-4 offset-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title ">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block content %}
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="" height="300px">
{% endblock content %}

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-4 offset-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title ">
                        Signup
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}